services:
    ros1:
        build:
            context: .
            dockerfile: .docker_utils/Dockerfile
            args:
                - ROS_DISTRO=noetic
        image: r-carla:noetic
        privileged: true
        container_name: rcarla-ros1
        network_mode: "host"
        
        command: tail -f /dev/null
        volumes: 
            - ./rcarla_bringup:/opt/ws/src/rcarla_bringup
            - ./drive_interface:/opt/ws/src/drive_interface
    ros2:
        build:
            context: .
            dockerfile: .docker_utils/Dockerfile
            args:
                - ROS_DISTRO=foxy
        image: r-carla:foxy
        privileged: true
        container_name: rcarla-ros2
        network_mode: "host"
        ipc: "host"
        command: tail -f /dev/null
        volumes: 
            - ./rcarla_bringup:/opt/ws/src/rcarla_bringup
    
